#!/usr/bin/env node
/* ============================================================================
   SCALE TEST — what happens at 100, 300 and 500 guides.

   The architecture was designed for a library roughly fifteen times the size
   of the current one, and 31 guides will not tell you whether it works. So
   this generates representative data at each size, runs the real build against
   it, measures what a reader would actually download, and puts everything back.

   Representative means representative: the synthetic guides are cloned from
   the real ones, so body lengths, panel structure, keyword counts, related
   links and age spreads all match the shape of the actual content rather than
   being uniformly small.

   Run with:  node tests/scale-test.js [sizes]
   e.g.       node tests/scale-test.js 31 100 300 500

   It restores data/guides-bundle.js and re-runs the normal build on the way
   out, including if it fails.
   ========================================================================== */

"use strict";

const fs = require("fs");
const path = require("path");
const zlib = require("zlib");
const { execFileSync } = require("child_process");

const ROOT = path.resolve(__dirname, "..");
const BUNDLE = path.join(ROOT, "data", "guides-bundle.js");
const BACKUP = path.join(ROOT, "data", ".guides-bundle.backup.js");

const SIZES = process.argv.slice(2).map(Number).filter(Boolean);
const TARGETS = SIZES.length ? SIZES : [31, 100, 300, 500];

const gz = (buf) => zlib.gzipSync(Buffer.from(buf), { level: 9 }).length;
const kb = (n) => (n / 1024).toFixed(1) + "KB";
const readIf = (p) => (fs.existsSync(p) ? fs.readFileSync(p) : Buffer.alloc(0));

/* Every file a browser fetches for a given page, resolved from its HTML. */
function pageWeight(htmlPath) {
  if (!fs.existsSync(htmlPath)) return null;
  const html = fs.readFileSync(htmlPath, "utf8");
  const assets = new Set();
  for (const m of html.matchAll(/<script[^>]*\bsrc="([^"]+)"/g)) assets.add(m[1]);
  for (const m of html.matchAll(/<link[^>]*\brel="stylesheet"[^>]*\bhref="([^"]+)"/g)) assets.add(m[1]);
  for (const m of html.matchAll(/<link[^>]*\bhref="([^"]+)"[^>]*\brel="stylesheet"/g)) assets.add(m[1]);

  let jsRaw = 0, jsGz = 0, cssRaw = 0, cssGz = 0, thirdParty = 0;
  for (const a of assets) {
    if (/^https?:/.test(a)) { thirdParty++; continue; }
    const rel = a.split("?")[0].replace(/^\//, "");
    const buf = readIf(path.join(ROOT, rel));
    if (!buf.length) continue;
    if (/\.js$/.test(rel)) { jsRaw += buf.length; jsGz += gz(buf); }
    else { cssRaw += buf.length; cssGz += gz(buf); }
  }
  const htmlBuf = Buffer.from(html);
  return {
    htmlRaw: htmlBuf.length, htmlGz: gz(htmlBuf),
    jsRaw, jsGz, cssRaw, cssGz, thirdParty,
    requests: assets.size + 1
  };
}

/* --------------------------------------------------------------------------
   Synthetic guides, cloned from the real ones so the shape is honest.
   ------------------------------------------------------------------------ */
function synthesise(real, target) {
  const out = real.slice();
  let i = 0;
  while (out.length < target) {
    const src = real[i % real.length];
    const n = out.length;
    const clone = JSON.parse(JSON.stringify(src));
    clone.id = `${src.id}-v${n}`;
    clone.title = `${src.title} (variant ${n})`;
    clone.order = n;
    clone.featured = n % 17 === 0;
    /* Related links point at real neighbours, so internal-link generation and
       the "Read next" block are exercised properly. */
    clone.related = [
      out[Math.max(0, n - 1)].id,
      out[Math.max(0, n - 2)].id,
      real[(i + 3) % real.length].id
    ].filter((v, idx, a) => v && v !== clone.id && a.indexOf(v) === idx);
    out.push(clone);
    i++;
  }
  return out.slice(0, target);
}

function writeBundle(guides, topics, ages) {
  const src =
    "/* GENERATED BY tests/scale-test.js — temporary. */\n" +
    `const AGES = ${JSON.stringify(ages)};\n` +
    `const ICONS = ${JSON.stringify(topics.reduce((a, t) => {
      a[t.id] = `<img src="/assets/img/icons/${t.id}.webp" alt="" aria-hidden="true">`;
      return a;
    }, {}))};\n` +
    `const TOPICS = ${JSON.stringify(topics.map(t =>
      ({ id: t.id, label: t.label, icon: `<img src="/assets/img/icons/${t.id}.webp" alt="" aria-hidden="true">` })))};\n` +
    "const topicById = id => TOPICS.find(t => t.id === id) || TOPICS[0];\n" +
    `var GUIDES = ${JSON.stringify(guides)};\n` +
    'if (typeof module === "object" && module.exports) module.exports = { AGES, TOPICS, ICONS, GUIDES, topicById };\n' +
    'if (typeof window !== "undefined") { window.GUIDES = GUIDES; window.AGES = AGES; window.TOPICS = TOPICS; window.ICONS = ICONS; window.topicById = topicById; }\n';
  fs.writeFileSync(BUNDLE, src);
}

function dirSize(dir) {
  if (!fs.existsSync(dir)) return 0;
  let total = 0;
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, e.name);
    total += e.isDirectory() ? dirSize(p) : fs.statSync(p).size;
  }
  return total;
}

function run() {
  const rows = [];
  const original = require("../data/guides-bundle.js");
  const realGuides = original.GUIDES;
  const topics = original.TOPICS;
  const ages = original.AGES;

  for (const target of TARGETS) {
    process.stdout.write(`  building ${target} guides… `);
    writeBundle(synthesise(realGuides, target), topics, ages);

    /* preferBundled is forced by the absence of network in this sandbox; on a
       machine with network the Firestore read would win, which is fine — the
       measurement is of the OUTPUT, not of where the data came from. */
    const t0 = Date.now();
    execFileSync("node", [path.join(ROOT, "scripts", "build.js")],
      { cwd: ROOT, stdio: "pipe" });
    const buildMs = Date.now() - t0;

    const idx = readIf(path.join(ROOT, "data/guide-index.json"));
    const srch = readIf(path.join(ROOT, "data/guide-search.json"));

    /* A real generated guide page — the one the whole exercise is about. */
    const slug = realGuides[0].id;
    const guide = pageWeight(path.join(ROOT, "guides", slug, "index.html"));
    const home = pageWeight(path.join(ROOT, "index.html"));
    const all = pageWeight(path.join(ROOT, "guides.html"));

    /* The old architecture, for comparison: every page also loaded the whole
       bundled catalogue. That is what these numbers replace. */
    const bundleRaw = fs.statSync(BUNDLE).size;

    rows.push({
      guides: target, buildMs,
      idxRaw: idx.length, idxGz: gz(idx),
      srchRaw: srch.length, srchGz: gz(srch),
      guideJsGz: guide ? guide.jsGz : 0,
      guideHtmlGz: guide ? guide.htmlGz : 0,
      guideReq: guide ? guide.requests : 0,
      homeJsGz: home ? home.jsGz : 0,
      allHtmlGz: all ? all.htmlGz : 0,
      oldPerPageRaw: bundleRaw,
      siteBytes: dirSize(path.join(ROOT, "guides")) +
                 dirSize(path.join(ROOT, "topics")) +
                 dirSize(path.join(ROOT, "ages"))
    });
    console.log(`${buildMs}ms`);
  }

  /* ---- report --------------------------------------------------------- */
  const line = (l, f) => console.log("  " + l.padEnd(34) +
    rows.map(r => String(f(r)).padStart(13)).join(""));

  console.log("\n" + "=".repeat(34 + 13 * rows.length));
  console.log("  SCALE".padEnd(34) + rows.map(r => String(r.guides + " guides").padStart(13)).join(""));
  console.log("=".repeat(34 + 13 * rows.length));

  console.log("\n  ONE GUIDE PAGE — what a reader downloads");
  line("HTML (gzipped)", r => kb(r.guideHtmlGz));
  line("JavaScript (gzipped)", r => kb(r.guideJsGz));
  line("Requests", r => r.guideReq);
  line("...before this work", r => kb(r.oldPerPageRaw));

  console.log("\n  BROWSE PAGES");
  line("guides.html HTML (gzipped)", r => kb(r.allHtmlGz));
  line("JavaScript (gzipped)", r => kb(r.homeJsGz));
  line("guide-index.json (gzipped)", r => kb(r.idxGz));
  line("guide-search.json (gzipped)", r => kb(r.srchGz));
  line("  ...index raw", r => kb(r.idxRaw));
  line("  ...search raw", r => kb(r.srchRaw));

  console.log("\n  BUILD");
  line("Build time", r => r.buildMs + "ms");
  line("Generated HTML on disk", r => kb(r.siteBytes));
  console.log("");
}

/* ------------------------------------------------------------------------ */
fs.copyFileSync(BUNDLE, BACKUP);
try {
  run();
} finally {
  fs.copyFileSync(BACKUP, BUNDLE);
  fs.unlinkSync(BACKUP);
  /* Put the real site back, whatever happened above. */
  execFileSync("node", [path.join(ROOT, "scripts", "build.js")], { cwd: ROOT, stdio: "pipe" });
  console.log("  Temporary data removed; the real site has been rebuilt.\n");
}
