/* ============================================================================
   SOCIAL — THE POSTER RENDERER

   One renderer, two consumers:

     • the /social/ dashboard, which scales the markup down for preview
     • scripts/social-render.js, which screenshots it at full size

   Both use THIS file, so what Amir approves on screen is what would be
   exported. A preview drawn by different code from the export is a preview of
   nothing.

   ---------------------------------------------------------------------------
   WHAT THIS FILE REPLACED, AND WHY

   The old renderer drew a cream page with a heading and a rounded card of
   bullet points, once per slide. It was correct, safe, legible and completely
   inert — a website panel enlarged to 1080 pixels. Nobody stops scrolling for
   a page.

   The approved poster references are built out of five things, and so is this:

     1. a painted FIELD — deep blue or warm cream, edge to edge
     2. a torn CREAM SHEET sitting askew on top of it
     3. CHARACTER CUTOUTS, grouped, overlapping and cropped by the bottom edge
     4. a HEADLINE in two or three colours at two or three sizes
     5. hand-drawn MARKS — sparks, arrows, an outlined heart, a brush underline

   ---------------------------------------------------------------------------
   TWO LAYERS, AND THE REASON THEY ARE SEPARATE

     .s-scene   the artwork. Either an image generated by the model from the
                approved references, or — when there is none — a composition
                built here from the approved cutouts and painted shapes.
     .s-type    every readable word, drawn by this file from text that has
                already been through condense.js and safety.js.

   Nothing readable is ever inside .s-scene. That is what lets a medical
   warning be illustrated AND exact: the picture can be generated, the words
   cannot. If a generated base comes back with letters in it, artwork.js
   rejects it and this renderer falls back to the composed scene — which never
   contains a word either.

   ---------------------------------------------------------------------------
   NO FILTER EVER TOUCHES A LETTER

   The torn-paper and brush effects are feTurbulence displacement filters. A
   displacement filter applied to an element containing text displaces the text
   too, and at label sizes that is not a texture, it is a typo: an early build
   of this file rendered "Try a dim, quiet room" as "TAY A DIM, QUIET ROOM"
   because the chip and its words were one filtered element.

   So every painted chip is TWO elements — a filtered background and an
   unfiltered text node on top of it (see chip() below). The rule is absolute:
   if a node has text in it, it has no filter on it. The exported words have to
   be the approved words, character for character.
   ---------------------------------------------------------------------------
   Runs in Node and in the browser: CommonJS when there is a module, a global
   otherwise.
   ========================================================================== */
(function (root, factory) {
  const api = factory();
  if (typeof module === "object" && module.exports) module.exports = api;
  else root.MPCSocialTemplates = api;
})(typeof self !== "undefined" ? self : this, function () {

  const esc = (s) => String(s == null ? "" : s)
    .replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");

  /* --------------------------------------------------------------------------
     SAFE AREAS

     Instagram draws its own furniture over a Story — the profile row at the
     top, the reply box at the bottom. These are the margins that keep our
     words clear of it. The carousel has no overlay, but 72px of air stops the
     type touching the edge of a phone screen.
     ------------------------------------------------------------------------ */
  const SAFE = {
    carousel: { top: 72,  right: 72,  bottom: 72,  left: 72 },
    story:    { top: 250, right: 78,  bottom: 260, left: 78 }
  };

  const SIZE = {
    carousel: { width: 1080, height: 1350 },
    story:    { width: 1080, height: 1920 }
  };

  /* --------------------------------------------------------------------------
     THE APPROVED CUTOUTS

     Taken from assets/img/refs/manifest.json — the character sheets marked
     `cutout`, with the transparent padding around them expressed as a crop
     box. `aspect` is the cropped region's width÷height, which is what lets a
     figure be positioned by HEIGHT alone: the only measurement that matters
     when a character is standing on the bottom edge of a poster.

     These are the approved drawings. Nothing here generates a person.
     ------------------------------------------------------------------------ */
  const CHARACTERS = {
    mama: { src: "/assets/img/refs/mama.png", box: [0, 0, 1, 1],                 aspect: 0.434 },
    papa: { src: "/assets/img/refs/papa.png", box: [0, 0, 1, 1],                 aspect: 0.414 },
    ari:  { src: "/assets/img/refs/ari.png",  box: [0.081, 0.079, 0.921, 0.813], aspect: 0.796 }
  };

  /* mpc-logo.png, not logo.png. logo.png is fully opaque with a black matte
     baked behind it — dropped onto a poster it renders as a black rectangle
     with the badge inside. mpc-logo.png is the same lockup with a real alpha
     channel. */
  const BRAND = {
    logo:  "/assets/img/mpc-logo.png",
    paper: "/assets/img/paper.jpg"
  };

  /* Asset resolution. The dashboard hands over real site paths; the export
     renderer hands over data URIs, because its page has an opaque origin from
     setContent() and a root-absolute path would not resolve. Same functions,
     same layout, same pixels — only the bytes arrive differently. */
  function resolve(ctx, p) {
    const map = (ctx && ctx.assets && ctx.assets.images) || {};
    return map[p] || p;
  }

  /* --------------------------------------------------------------------------
     COLOUR

     compose.js chooses names ("ink", "orange"); this file is the only place
     that knows what they look like. The values are the poster palette sampled
     from the approved references, and they live on .mpc-slide rather than in
     tokens.css because tokens.css is downloaded by every reader of the public
     site and none of these appear there.
     ------------------------------------------------------------------------ */
  /* THE PALETTE IS assets/css/tokens.css, BY VALUE.

     The first version of this file invented its own: a #215d9c navy, a #dc5019
     vermilion and a #cb4a22 red, chosen by eye from the poster references. Put
     together as full-width bands under heavy all-caps they produced a wartime
     recruitment notice — which is what happens when you pair navy and red at
     full saturation and block them across a frame.

     These are the site's own tokens, and they are softer on purpose:
     --blue-ink #3f6fa3 is a pen, not a flag, and --red-ink #d4553a is a warning
     rather than an alarm. The UI colours --blue #0b62c4 and --orange #ff4500
     are deliberately NOT here: they are for things a reader clicks. */
  const INK = {
    ink:        "var(--mpc-ink)",          /* #211d18 */
    inkHand:    "var(--mpc-ink-hand)",     /* #2b2622 */
    blue:       "var(--mpc-blue)",         /* #3f6fa3 — the drawn blue */
    bluePale:   "var(--mpc-blue-pale)",    /* #c9dced */
    blueWash:   "var(--mpc-blue-wash)",    /* #e7f0fb */
    orange:     "var(--mpc-orange)",       /* #e2601f — the drawn orange */
    coral:      "var(--mpc-coral)",        /* #d4553a — warnings only */
    coralFill:  "var(--mpc-coral-fill)",   /* #f9e2da */
    amber:      "var(--mpc-amber)",        /* #c07f1e */
    amberFill:  "var(--mpc-amber-fill)",   /* #fdf1d8 */
    cream:      "var(--mpc-cream)",        /* #fbf0d3 */
    creamSoft:  "var(--mpc-cream-soft)",   /* #fdf8ec */
    paper:      "var(--mpc-paper)",        /* #f7ecd2 */
    creamDeep:  "var(--mpc-paper)",
    /* legacy names kept so an older stored package still renders */
    yellow:     "var(--mpc-amber)",
    red:        "var(--mpc-coral)",
    white:      "#fff"
  };
  const inkOf = (name) => INK[name] || INK.ink;

  /* Which colour the ground under the type is, per family. A kicker pill has
     to contrast with what it sits on, and "blue pill" is invisible on a blue
     field — the sort of thing that only shows up once it is exported. */
  /* Every slide is now on paper. The full-bleed blue field is gone: an
     edge-to-edge dark ground with type reversed out of it is the single
     strongest propaganda-poster cue, and it was on three of the seven
     families. Blue survives as a PATCH — a brushed shape with an uneven edge
     that the scene sits on — which is what the approved references actually
     do. */
  const GROUND = {
    "cover-hook": "cream", "dont": "cream", "story-reel": "cream",
    "quick-check": "cream", "what-helped-us": "cream", "warning": "cream", "save-cta": "cream"
  };
  const onBlue = () => false;

  /* --------------------------------------------------------------------------
     TYPE SIZE

     Baloo 2 at weight 800, uppercase, averages about 0.575em of advance per
     character. To fill a box `boxW` wide with `n` characters:

         size = boxW / (n * 0.575)

     clamped, so a two-character line is not 400px tall and a very long one is
     still readable. That is where most of the "designed" feeling comes from,
     and it costs one division: a short line comes out enormous and a long one
     merely large, which is exactly what a hand-lettered poster does.

     It is computed in JS rather than CSS because the dashboard and the export
     renderer must agree to the pixel, and a container query would resolve
     differently inside a scaled preview.
     ------------------------------------------------------------------------ */
  /* Measured, not guessed: Baloo 2 800 uppercase with the -0.014em tracking
     this file sets runs between 0.498 and 0.568 em of advance per character
     across the real headlines in the guide library, averaging 0.52. 0.55 sits
     just above the average, so a typical line fills its box and the widest
     ones stay inside it — which is why every `boxW` passed in below is a
     little narrower than the block it sits in. */
  const ADVANCE = 0.55;

  /* The absolute floor. `min` below is the PREFERRED minimum — the size below
     which a headline stops being a headline — but it is not a hard stop,
     because a line that will not fit at the preferred minimum has to do
     something, and running off the edge of the slide is the worst of the
     available options.

     So a line that cannot fit shrinks past the preference down to 32px, and
     validate.js raises `headline-long` so the operator is told to shorten it
     rather than discovering it in the feed. Overflow is a bug; small type on
     a twenty-word quick answer is a message. */
  const HARD_MIN = 32;

  function fitSize(text, boxW, min, max) {
    const n = Math.max(1, String(text || "").trim().length);
    const ideal = boxW / (n * ADVANCE);
    if (ideal >= min) return Math.round(Math.min(max, ideal));
    return Math.round(Math.max(HARD_MIN, ideal));
  }

  /* A tiny stable hash, so decoration is varied but identical every time. */
  function hash(s) {
    let h = 2166136261;
    const str = String(s || "");
    for (let i = 0; i < str.length; i++) { h ^= str.charCodeAt(i); h = Math.imul(h, 16777619); }
    return Math.abs(h | 0);
  }

  /* --------------------------------------------------------------------------
     SVG FILTERS

     feTurbulence + feDisplacementMap is what turns a rectangle into a torn
     sheet of paper and a straight-edged band into a brush stroke. Applied to
     HTML elements, not images, so the shapes stay resolution independent and
     recolourable.

     They have to exist ONCE in the document. documentHTML() writes them; the
     dashboard appends T.FILTERS to the page.

     NONE OF THESE MAY BE PUT ON AN ELEMENT CONTAINING TEXT. See the header.
     ------------------------------------------------------------------------ */
  const FILTERS = `
<svg id="mpc-filter-defs" width="0" height="0" style="position:absolute;left:-9999px" aria-hidden="true"><defs>
  <filter id="mpcTorn" x="-10%" y="-10%" width="120%" height="120%" filterUnits="objectBoundingBox">
    <feTurbulence type="fractalNoise" baseFrequency="0.008 0.035" numOctaves="5" seed="7" result="n"/>
    <feDisplacementMap in="SourceGraphic" in2="n" scale="34" xChannelSelector="R" yChannelSelector="G"/>
  </filter>
  <filter id="mpcTornFine" x="-12%" y="-14%" width="124%" height="128%" filterUnits="objectBoundingBox">
    <feTurbulence type="fractalNoise" baseFrequency="0.02 0.07" numOctaves="4" seed="19" result="n"/>
    <feDisplacementMap in="SourceGraphic" in2="n" scale="15" xChannelSelector="R" yChannelSelector="G"/>
  </filter>
  <filter id="mpcBrush" x="-14%" y="-18%" width="128%" height="136%" filterUnits="objectBoundingBox">
    <feTurbulence type="fractalNoise" baseFrequency="0.012 0.05" numOctaves="4" seed="3" result="n"/>
    <feDisplacementMap in="SourceGraphic" in2="n" scale="40" xChannelSelector="R" yChannelSelector="G"/>
  </filter>
  <filter id="mpcWash" x="-16%" y="-20%" width="132%" height="140%" filterUnits="objectBoundingBox">
    <feTurbulence type="fractalNoise" baseFrequency="0.02 0.04" numOctaves="3" seed="23" result="n"/>
    <feDisplacementMap in="SourceGraphic" in2="n" scale="58" xChannelSelector="R" yChannelSelector="G"/>
  </filter>
</defs></svg>`;

  /* --------------------------------------------------------------------------
     A PAINTED CHIP

     Background and text as separate nodes, because the background is filtered
     and the text must never be. Every pill, band, label and disc goes through
     this.
     ------------------------------------------------------------------------ */
  function chip(cls, bgColour, text, opts) {
    const o = opts || {};
    return `<span class="${cls}"${o.style ? ` style="${o.style}"` : ""}>` +
      `<span class="c-bg" style="background:${inkOf(bgColour)}${o.bgFilter ? `;filter:url(#${o.bgFilter})` : ""}"></span>` +
      `<span class="c-t"${o.textStyle ? ` style="${o.textStyle}"` : ""}>${esc(text)}</span></span>`;
  }

  /* --------------------------------------------------------------------------
     HAND-DRAWN MARKS
     ------------------------------------------------------------------------ */
  function sparks(colour, n, seed, area) {
    const c = inkOf(colour);
    const a = area || { x: 3, y: 4, w: 94, h: 92 };
    let out = "";
    for (let i = 0; i < n; i++) {
      const h = hash(seed + ":" + i);
      const x = a.x + (h % a.w);
      const y = a.y + ((h >> 7) % a.h);
      const s = 30 + ((h >> 13) % 34);
      const r = (h >> 17) % 360;
      out += `<span class="b-spark" style="left:${x}%;top:${y}%;width:${s}px;height:${s}px;` +
        `transform:rotate(${r}deg);color:${c}"><svg viewBox="0 0 40 40" fill="none" stroke="currentColor" ` +
        `stroke-width="5" stroke-linecap="round"><path d="M20 3v11M33 9l-8 8M37 22H26"/></svg></span>`;
    }
    return out;
  }

  const heartMark = (colour, style) =>
    `<span class="b-mark" style="${style};color:${inkOf(colour)}"><svg viewBox="0 0 48 44" fill="none" ` +
    `stroke="currentColor" stroke-width="4" stroke-linejoin="round"><path d="M24 40C10 30 4 23 4 15.5 4 9 9 5 14.5 5 18.6 5 21.8 7.2 24 10.6 26.2 7.2 29.4 5 33.5 5 39 5 44 9 44 15.5 44 23 38 30 24 40Z"/></svg></span>`;

  const arrowMark = (colour, style) =>
    `<span class="b-mark" style="${style};color:${inkOf(colour)}"><svg viewBox="0 0 160 60" fill="none" ` +
    `stroke="currentColor" stroke-width="8" stroke-linecap="round" stroke-linejoin="round">` +
    `<path d="M6 42c30-28 78-34 142-24"/><path d="M124 4l24 15-20 19"/></svg></span>`;

  /* --------------------------------------------------------------------------
     OBJECT CLUES

     One drawn object per label, inked in the brand palette on a torn paper
     disc. Chosen by compose.js objectFor() from the label's own words; an
     unmatched label gets a number instead, which is what the numbered-path
     variant is for.

     Stroke-built rather than illustrated, because these are drawn by the
     RENDERER. The illustrated versions are what the model puts into the base
     when one has been generated; these are what the composed fallback uses,
     and round caps and uneven weights keep them in the same handwriting as
     the rest of the poster.
     ------------------------------------------------------------------------ */
  const OBJECT_PATHS = {
    bottle:      '<path d="M40 10h20M43 10v11c0 5-9 9-9 17v37c0 6 4 10 10 10h12c6 0 10-4 10-10V38c0-8-9-12-9-17V10"/><path d="M35 45h30"/>',
    spoon:       '<path d="M50 90V48"/><ellipse cx="50" cy="30" rx="15" ry="19"/>',
    thermometer: '<path d="M42 16a8 8 0 0 1 16 0v42a14 14 0 1 1-16 0Z"/><path d="M50 36v28"/><path d="M64 28h10M64 40h8M64 52h10"/>',
    nose:        '<path d="M52 12c-4 18-13 28-19 38-4 7 0 12 8 12"/><path d="M28 66c9 12 35 12 44 0"/><path d="M63 60c6-1 9-6 5-13-6-10-14-19-18-33"/>',
    mouth:       '<path d="M14 44c14-13 58-13 72 0-9 25-63 25-72 0Z"/><path d="M30 51c10 15 30 15 40 0"/>',
    tooth:       '<path d="M27 25c0-8 10-13 23-13s23 5 23 13c0 14-6 21-8 35-2 12-10 22-14 22s-6-14-8-22c-2 8-4 22-8 22s-12-10-14-22c-2-14-8-21-8-35"/>',
    nappy:       '<path d="M15 26h70c0 27-11 41-35 60C26 67 15 53 15 26Z"/><path d="M50 34v32"/>',
    moon:        '<path d="M67 14a35 35 0 1 0 19 46 29 29 0 0 1-19-46Z"/>',
    sun:         '<circle cx="50" cy="50" r="19"/><path d="M50 10v11M50 79v11M10 50h11M79 50h11M22 22l8 8M70 70l8 8M78 22l-8 8M30 70l-8 8"/>',
    clock:       '<circle cx="50" cy="52" r="35"/><path d="M50 28v24l17 11"/>',
    drop:        '<path d="M50 10c15 21 25 33 25 45a25 25 0 1 1-50 0c0-12 10-24 25-45Z"/>',
    weight:      '<path d="M20 86 31 28h38l11 58Z"/><path d="M39 28v-8a11 11 0 0 1 22 0v8"/>',
    eye:         '<path d="M8 50c15-19 69-19 84 0-15 19-69 19-84 0Z"/><circle cx="50" cy="50" r="13"/>',
    skin:        '<path d="M15 45c10-19 60-19 70 0 10 19-11 42-35 42S5 64 15 45Z"/><circle cx="37" cy="47" r="4.5"/><circle cx="59" cy="41" r="4.5"/><circle cx="54" cy="65" r="4.5"/>',
    sleepy:      '<circle cx="50" cy="50" r="35"/><path d="M31 43c5-5 11-5 16 0M53 43c5-5 11-5 16 0M35 66c9-7 21-7 30 0"/>',
    sick:        '<path d="M29 16h42v36a21 21 0 0 1-42 0Z"/><path d="M39 72c0 9 5 15 11 15s11-6 11-15"/>',
    toy:         '<circle cx="50" cy="57" r="27"/><path d="M50 30V12M37 16l13 13 13-13"/>',
    home:        '<path d="M14 50 50 18l36 32"/><path d="M25 45v38h50V45"/><path d="M41 83V59h18v24"/>',
    pause:       '<circle cx="50" cy="50" r="35"/><path d="M42 35v30M58 35v30"/>',
    smile:       '<circle cx="50" cy="50" r="35"/><path d="M36 41h.1M64 41h.1M33 60c9 11 25 11 34 0"/>',
    heart:       '<path d="M50 86C23 67 13 55 13 40 13 26 24 18 34 18c7 0 13 4 16 9 3-5 9-9 16-9 10 0 21 8 21 22 0 15-10 27-37 46Z"/>',
    phone:       '<path d="M29 12h42v76H29Z"/><path d="M43 79h14"/>',
    book:        '<path d="M12 21h30c5 0 8 3 8 8v56c0-5-3-8-8-8H12Z"/><path d="M88 21H58c-5 0-8 3-8 8v56c0-5 3-8 8-8h30Z"/>',
    person:      '<circle cx="50" cy="29" r="17"/><path d="M16 90c0-19 15-32 34-32s34 13 34 32"/>'
  };

  function objectSVG(name) {
    const d = OBJECT_PATHS[name];
    if (!d) return "";
    return `<svg viewBox="0 0 100 100" fill="none" stroke="currentColor" stroke-width="7" ` +
      `stroke-linecap="round" stroke-linejoin="round">${d}</svg>`;
  }

  /* ==========================================================================
     THE SCENE — the artwork layer

     Either the generated base, or a composition built from approved cutouts
     and painted shapes. Nothing in here is ever readable.
     ======================================================================== */

  function charHTML(name, ctx, style) {
    const c = CHARACTERS[name];
    if (!c) return "";
    const l = c.box[0], t = c.box[1], r = c.box[2], b = c.box[3];
    const w = 100 / (r - l), h = 100 / (b - t);
    return `<div class="b-char" style="${style};--ar:${c.aspect}">` +
      `<img src="${esc(resolve(ctx, c.src))}" alt="" style="width:${w}%;height:${h}%;` +
      `left:${-l * w}%;top:${-t * h}%">` +
      `</div>`;
  }

  const sheetShape = (style) => `<div class="b-sheet" style="${style}"></div>`;
  const bandShape  = (style, colour, filter) =>
    `<div class="b-band" style="${style};background:${inkOf(colour)};filter:url(#${filter || "mpcBrush"})"></div>`;
  const washShape  = (style, colour) =>
    `<div class="b-wash" style="${style};background:${inkOf(colour)}"></div>`;

  /* THE CAST, POSITIONED.

     The figures are placed as a GROUP, sized so their widths add up to more
     than the canvas and they overlap — three cutouts spaced evenly across a
     flat field read as three stickers, which is what the first build of this
     looked like. Overlapping them, cropping them on the bottom edge and
     putting a painted ground under them is what makes them a family sitting
     somewhere.

     Heights are a percentage of the SLIDE height, so a Story gets the same
     figures at the same relative scale as a carousel slide.  */
  function castHTML(cast, ctx, plan) {
    const list = (cast && cast.length ? cast : ["mama", "papa", "ari"]);
    const has = (n) => list.indexOf(n) >= 0;
    const p = plan || {};
    const bottom = p.bottom == null ? -5 : p.bottom;
    const pair = has("mama") && has("papa");
    const out = [];

    if (p.ground !== false) {
      out.push(`<div class="b-patch" style="left:-10%;bottom:${bottom - 5}%;width:120%;` +
        `height:${p.groundH || 26}%;border-radius:52% 48% 0 0 / 44% 40% 0 0;` +
        `opacity:${p.groundOpacity == null ? 0.5 : p.groundOpacity};` +
        `background:${inkOf(p.groundColour || "bluePale")};filter:url(#mpcWash)"></div>`);
    }

    /* ONE PARENT IS A DIFFERENT COMPOSITION, NOT A GAP.

       castHTML used to anchor Papa to the right edge and Mama to the left,
       which works for a pair and falls apart the moment a concept asks for a
       single adult: Papa stayed pinned right while Ari sat at her usual
       left-of-centre spot, and the two of them overlapped into one shape with
       a head sticking out of it. A solo parent is placed explicitly, and Ari
       is placed beside them rather than at the group position. */
    if (!pair && (has("mama") || has("papa"))) {
      const who = has("mama") ? "mama" : "papa";
      const left = p.parentLeft == null ? 4 : p.parentLeft;
      out.push(charHTML(who, ctx,
        `left:${left}%;bottom:${bottom}%;height:${p.parentH || p.papaH || 56}%;z-index:3`));
      if (has("ari")) {
        out.push(charHTML("ari", ctx,
          `left:${p.ariLeft == null ? left + 26 : p.ariLeft}%;bottom:${bottom + 1}%;` +
          `height:${p.ariH || 32}%;z-index:4`));
      }
      return out.join("");
    }

    if (has("papa")) {
      out.push(charHTML("papa", ctx,
        `right:${p.papaRight == null ? -6 : p.papaRight}%;bottom:${bottom}%;` +
        `height:${p.papaH || 58}%;z-index:3`));
    }
    if (has("mama")) {
      out.push(charHTML("mama", ctx,
        `left:${p.mamaLeft == null ? -5 : p.mamaLeft}%;bottom:${bottom + 1}%;` +
        `height:${p.mamaH || 54}%;z-index:2`));
    }
    if (has("ari")) {
      out.push(charHTML("ari", ctx,
        `left:${p.ariLeft == null ? 31 : p.ariLeft}%;bottom:${bottom + 1}%;` +
        `height:${p.ariH || 33}%;z-index:4`));
    }
    /* Ari alone. */
    if (!has("mama") && !has("papa") && has("ari")) return out.join("");
    return out.join("");
  }

  /* ---- soft shapes -------------------------------------------------------
     A patch, not a band. Every one of these is irregular: uneven corner radii,
     a rotation, a brush filter on the edge. The rectangle is what made the
     first version look like a notice, so there are no rectangles left. */
  function patch(style, colour, opts) {
    const o = opts || {};
    const r = o.radius || "48% 52% 44% 56% / 56% 44% 56% 44%";
    return `<div class="b-patch" style="${style};background:${inkOf(colour)};` +
      `border-radius:${r};opacity:${o.opacity == null ? 1 : o.opacity};` +
      `filter:url(#${o.filter || "mpcWash"})"></div>`;
  }

  /* A torn scrap of paper. Slightly different every time, seeded by its own
     position, so no two scraps on a slide are the same shape. */
  function scrap(style, seed, colour) {
    const h = hash(String(seed));
    const rot = ((h % 90) / 10 - 4.5).toFixed(1);
    const r = 2 + (h % 5);
    return `<div class="b-scrap" style="${style};background:${inkOf(colour || "paper")};` +
      `border-radius:${r}px;transform:rotate(${rot}deg);filter:url(#mpcTorn)"></div>`;
  }

  /* A loose hand-drawn circle, the kind you put round something in a notebook. */
  const looseCircle = (style, colour) =>
    `<span class="b-mark" style="${style};color:${inkOf(colour)}"><svg viewBox="0 0 120 110" ` +
    `fill="none" stroke="currentColor" stroke-width="4" stroke-linecap="round">` +
    `<path d="M62 6C31 4 8 26 7 55c-1 30 24 50 55 49 30-1 52-21 52-49C114 26 92 8 62 6"/>` +
    `<path d="M70 9c26 4 42 22 43 45"/></svg></span>`;

  /* A scribbled underline, two passes, like a biro. */
  const scribble = (style, colour) =>
    `<span class="b-mark" style="${style};color:${inkOf(colour)}"><svg viewBox="0 0 240 24" ` +
    `preserveAspectRatio="none" fill="none" stroke="currentColor" stroke-width="5" ` +
    `stroke-linecap="round"><path d="M4 12c46-6 92-8 138-6 34 1 66 4 94 9"/>` +
    `<path d="M14 19c44-5 88-7 132-5 32 1 62 3 88 7"/></svg></span>`;

  /* ---- object props ------------------------------------------------------
     The concept names the objects that belong in the scene. Drawn here as
     inked shapes on their own scraps of paper, at scene scale rather than
     label scale, so a warning slide has a nappy and a bottle in it and a
     helped slide has a lamp — which is a large part of what stops two slides
     looking the same. */
  function prop(name, style, colour, size) {
    const glyph = objectSVG(name);
    if (!glyph) return "";
    return `<span class="b-prop" style="${style};width:${size}px;height:${size}px;` +
      `color:${inkOf(colour || "ink")}">` +
      `<span class="b-prop-bg"></span><span class="b-prop-art">${glyph}</span></span>`;
  }

  const conceptOf = (slide) => (slide && slide.concept) || null;
  const propsOf = (slide, n) => {
    const c = conceptOf(slide);
    return ((c && c.objects) || []).filter(o => OBJECT_PATHS[o]).slice(0, n || 2);
  };

  /* ---- per-family scenes -------------------------------------------------

     Each of these has a materially different CAST, CROP, SCALE and OBJECT
     TREATMENT. That is the correction: they used to differ only in which
     painted rectangles sat behind the same seated line-up, so a reader
     scrolling the carousel saw one picture six times.

       cover      the group, mid-shot, on a blue patch, one object prop large
       quick      ONE parent and Ari, cropped close and pushed off-centre
       normal     NO figures at all — a flat-lay of objects on torn scraps
       helped     ONE parent and Ari, small, in a lot of empty amber-washed paper
       warning    ONE parent and Ari, quiet, under a soft coral patch
       dont       ONE parent and Ari, off-centre, objects circled at the foot
       save       the group, wide and low, the warmest slide
       story      vertical, tight, stacked

     ------------------------------------------------------------------------ */

  /* --------------------------------------------------------------------------
     THE COVER'S GEOMETRY

     The torn sheet, the logo badge and the category pill all have to know how
     tall the headline is, and that is decided by the guide's own question —
     "Why is my baby drinking less milk?" sets one height and "Is it normal to
     feel like I can't handle one more person touching me?" sets another, so a
     fixed sheet is wrong for one of them whichever number you pick. Guessing
     from the line COUNT was the first attempt and it put the badge on Papa's
     head.

     Computed from the same fitSize() the type uses, once, so the dashboard
     preview and the export agree.
     ------------------------------------------------------------------------ */
  const LOGO_W = 196;
  const LOGO_RATIO = 331 / 760;          /* mpc-logo.png */

  function coverGeometry(slide) {
    const H = SIZE.carousel.height;
    const lines = (slide.lines || []).filter(l => l && String(l.t || "").trim());
    const topPct = 5;
    const topPx = H * topPct / 100;

    const headPx = lines.reduce((t, l) =>
      t + fitSize(l.em ? String(l.t).toUpperCase() : l.t, 850, 54, 138), 0) * 1.02;
    const logoPx = slide.logo ? LOGO_W * LOGO_RATIO : 0;
    const gap = slide.logo ? 46 : 0;

    const logoTopPx = topPx + headPx + gap;
    const sheetBottomPx = logoTopPx + logoPx + 44;

    const sheetTop = topPct - 3;
    const sheetBottom = Math.max(sheetTop + 25, Math.min(sheetTop + 52, (sheetBottomPx / H) * 100));
    const r = (n) => Math.round(n * 10) / 10;
    return {
      topPct,
      sheetTop: r(sheetTop),
      sheetH: r(sheetBottom - sheetTop),
      sheetBottom: r(sheetBottom),
      logoTop: r((logoTopPx / H) * 100)
    };
  }

  function sceneCover(slide, ctx) {
    const v = slide.variant || "character-bottom";
    const seed = (slide.lines || []).map(l => l.t).join("");
    const geo = coverGeometry(slide);
    let out = `<div class="b-field" style="background:${INK.cream}"></div>`;

    /* One soft blue patch for the group to sit on — brushed, uneven, and
       nowhere near the edges of the frame. */
    out += patch("left:-8%;bottom:-6%;width:96%;height:40%", "bluePale",
      { opacity: .95, radius: "44% 56% 0 0 / 62% 38% 0 0" });
    out += patch("left:-14%;bottom:-8%;width:52%;height:26%", "blue",
      { opacity: .22, radius: "50% 50% 0 0 / 70% 30% 0 0" });

    out += scrap(`left:${v === "split-character" ? 1 : 2}%;top:${geo.sheetTop}%;` +
      `width:${v === "split-character" ? 97 : 95}%;height:${geo.sheetH}%`, "cover" + seed, "creamSoft");

    const ground = { ground: false };
    if (v === "detail-crop") {
      out += castHTML(slide.cast, ctx, Object.assign(
        { bottom: -12, papaH: 62, mamaH: 58, ariH: 37, papaRight: 4, mamaLeft: 2, ariLeft: 34 }, ground));
    } else if (v === "split-character") {
      out += castHTML(slide.cast, ctx, Object.assign(
        { bottom: -6, papaH: 55, mamaH: 51, ariH: 33, papaRight: -2, mamaLeft: 1, ariLeft: 36 }, ground));
    } else {
      out += castHTML(slide.cast, ctx, Object.assign(
        { bottom: -5, papaH: 53, mamaH: 49, ariH: 32, papaRight: 1, mamaLeft: 2, ariLeft: 34 }, ground));
    }

    /* The object the guide is about, drawn once and large, beside the group. */
    /* No object prop on the cover: the group is already holding the thing the
       guide is about, and a second copy of it floating beside their heads is
       the sort of detail that reads as a mistake. */
    const strip = geo.sheetBottom + 2;
    out += sparks("orange", 2, seed + "o", { x: 8, y: strip, w: 22, h: 5 });
    out += heartMark("orange", `left:80%;top:${strip}%;width:48px;height:44px;transform:rotate(-11deg)`);
    return out;
  }

  function sceneQuickCheck(slide, ctx) {
    const items = slide.items || [];
    const clueSlide = items.length > 0;
    const seed = (slide.lines || []).map(l => l.t).join("");
    let out = `<div class="b-field" style="background:${INK.cream}"></div>`;

    if (clueSlide) {
      /* THE CLUE SLIDE HAS NO PEOPLE IN IT.

         This is the biggest single change. It used to draw the same parent and
         baby as the slide before it and hang four labels round them; now it is
         a flat-lay — the objects the guide's own words name, each on its own
         scrap of paper at its own angle, with one small drawing of Ari tucked
         into a corner reacting to them. Different cast, different distance,
         different subject. */
      out += patch("right:-16%;top:-10%;width:52%;height:30%", "amberFill",
        { opacity: .9, radius: "42% 58% 60% 40% / 50% 40% 60% 50%" });
      out += patch("left:-18%;bottom:-10%;width:50%;height:28%", "blueWash",
        { opacity: .95, radius: "56% 44% 40% 60% / 44% 56% 44% 56%" });

      const objs = propsOf(slide, 4);
      objs.forEach((o, i) => {
        const sp = CLUE_SPOTS[i] || CLUE_SPOTS[0];
        out += scrap(`left:${sp.x}%;top:${sp.y}%;width:${Math.round(sp.s / 10.8)}%;` +
          `height:${Math.round(sp.s / 13.5)}%`, "clue" + i, "creamSoft");
        out += prop(o, `left:${sp.x + 2}%;top:${sp.y + 2}%;transform:rotate(${sp.r}deg)`,
          i % 2 ? "blue" : "orange", sp.s * 0.62);
      });
      /* Ari alone, small, in the corner — a reaction, not a line-up. */
      out += charHTML("ari", ctx, "right:5%;bottom:1%;height:26%;z-index:4");
      out += sparks("orange", 2, seed + "q", { x: 40, y: 20, w: 16, h: 6 });
      return out;
    }

    /* The quick ANSWER: one parent and Ari, close, off-centre, with the object
       lowered beside them. */
    out += patch("left:-14%;bottom:-8%;width:78%;height:36%", "bluePale",
      { opacity: .9, radius: "46% 54% 0 0 / 66% 34% 0 0" });
    out += patch("right:-14%;top:6%;width:38%;height:22%", "amberFill",
      { opacity: .9, radius: "56% 44% 46% 54% / 50% 50% 50% 50%" });
    out += castHTML(slide.cast, ctx, {
      ground: false, bottom: -8, parentLeft: 3, parentH: 64, ariH: 40, ariLeft: 44,
      papaRight: 30, mamaLeft: 3
    });
    const props = propsOf(slide, 1);
    if (props[0]) out += prop(props[0], "right:6%;top:40%;transform:rotate(-8deg)", "orange", 146);
    out += scribble("left:6%;top:31%;width:230px;height:22px;transform:rotate(-1.5deg)", "orange");
    return out;
  }

  function sceneHelped(slide, ctx) {
    const v = slide.variant || "steps-right";
    let out = `<div class="b-field" style="background:${INK.cream}"></div>`;
    /* The calmest, emptiest slide in the package. */
    out += patch("left:-16%;bottom:-12%;width:64%;height:38%", "amberFill",
      { opacity: .95, radius: "50% 50% 0 0 / 64% 36% 0 0" });
    out += patch("right:-18%;top:-12%;width:44%;height:26%", "blueWash",
      { opacity: .95, radius: "44% 56% 52% 48% / 52% 48% 52% 48%" });

    if (v === "steps-under") {
      out += castHTML(slide.cast, ctx, {
        ground: false, bottom: 26, parentLeft: 4, parentH: 46, ariH: 28, ariLeft: 30
      });
    } else {
      out += castHTML(slide.cast, ctx, {
        ground: false, bottom: -3, parentLeft: 2, parentH: 54, ariH: 32, ariLeft: 26
      });
    }
    const props = propsOf(slide, 2);
    if (props[0]) out += prop(props[0], "right:9%;top:26%;transform:rotate(-6deg)", "amber", 124);
    out += heartMark("orange", "left:8%;top:24%;width:44px;height:40px;transform:rotate(-8deg)");
    return out;
  }

  function sceneWarning(slide, ctx) {
    const v = slide.variant || "banner-discs";
    let out = `<div class="b-field" style="background:${INK.cream}"></div>`;
    /* A soft coral PATCH with an uneven edge, well inside the frame. Not a
       banner: a full-width red bar across the top of a poster is the exact
       thing that made this read as a wartime notice, and a warning does not
       need to shout to be taken seriously. */
    out += patch("left:2%;top:2%;width:86%;height:19%", "coralFill",
      { opacity: 1, radius: "8% 14% 10% 12% / 34% 26% 40% 30%", filter: "mpcBrush" });
    out += patch("left:4%;top:3.5%;width:56%;height:13%", "coral",
      { opacity: .13, radius: "14% 22% 16% 20% / 44% 36% 48% 40%", filter: "mpcBrush" });

    if (v === "banner-list") {
      out += castHTML(slide.cast, ctx, {
        ground: false, bottom: -4, parentLeft: 54, parentH: 48, ariH: 30, ariLeft: 76
      });
    } else {
      out += castHTML(slide.cast, ctx, {
        ground: false, bottom: -4, parentLeft: 52, parentH: 50, ariH: 31, ariLeft: 74
      });
    }
    /* The relevant everyday objects, small, on scraps low on the left — the
       side the labels do not occupy. */
    const props = propsOf(slide, 2);
    props.forEach((o, i) => {
      out += prop(o, `left:${i ? 24 : 8}%;bottom:${i ? 6 : 16}%;` +
        `transform:rotate(${i ? 7 : -6}deg)`, "coral", 112);
    });
    return out;
  }

  function sceneDont(slide, ctx) {
    let out = `<div class="b-field" style="background:${INK.cream}"></div>`;
    out += patch("right:-14%;bottom:-10%;width:62%;height:34%", "bluePale",
      { opacity: .9, radius: "52% 48% 0 0 / 62% 38% 0 0" });
    out += scrap("left:3%;top:2%;width:76%;height:26%", "dont", "creamSoft");
    out += castHTML(slide.cast, ctx, {
      ground: false, bottom: 18, parentLeft: 46, parentH: 50, ariH: 31, ariLeft: 70
    });
    const props = propsOf(slide, 1);
    if (props[0]) out += prop(props[0], "left:10%;bottom:36%;transform:rotate(-9deg)", "coral", 124);
    out += sparks("orange", 2, "dont", { x: 74, y: 30, w: 14, h: 6 });
    return out;
  }

  function sceneSave(slide, ctx) {
    const v = slide.variant || "family-close";
    let out = `<div class="b-field" style="background:${INK.cream}"></div>`;
    out += patch("left:-12%;bottom:-10%;width:124%;height:34%", "amberFill",
      { opacity: .95, radius: "40% 60% 0 0 / 58% 42% 0 0" });
    out += patch("left:6%;bottom:-6%;width:44%;height:20%", "blueWash",
      { opacity: .8, radius: "50% 50% 0 0 / 70% 30% 0 0" });
    if (v === "arrow-line") {
      out += castHTML(slide.cast, ctx, {
        ground: false, bottom: 14, papaH: 46, mamaH: 43, ariH: 28,
        papaRight: 3, mamaLeft: 3, ariLeft: 36
      });
    } else {
      out += castHTML(slide.cast, ctx, {
        ground: false, bottom: 14, papaH: 49, mamaH: 46, ariH: 30,
        papaRight: 0, mamaLeft: 0, ariLeft: 35
      });
    }
    out += scrap("left:-3%;bottom:-4%;width:106%;height:16%", "savefoot", "creamSoft");
    out += heartMark("orange", "right:11%;top:27%;width:46px;height:42px;transform:rotate(11deg)");
    out += sparks("blue", 2, "save", { x: 8, y: 30, w: 12, h: 5 });
    return out;
  }

  function sceneStory(slide, ctx) {
    const v = slide.variant || "torn-top";
    const items = slide.items || [];
    let out = `<div class="b-field" style="background:${INK.cream}"></div>`;

    if (v === "band-top") {
      out += patch("left:3%;top:11%;width:86%;height:14%", "coralFill",
        { opacity: 1, radius: "8% 14% 10% 12% / 36% 26% 40% 30%", filter: "mpcBrush" });
      out += scrap("left:2%;top:28.5%;width:95%;height:31%", "storysheet", "creamSoft");
    } else {
      out += scrap("left:2%;top:11%;width:95%;height:33%", "storysheet", "creamSoft");
    }
    /* A blue patch behind the lower half only — never the whole frame. */
    out += patch("left:-10%;bottom:-6%;width:120%;height:36%", "bluePale",
      { opacity: .95, radius: "44% 56% 0 0 / 40% 60% 0 0" });

    out += castHTML(slide.cast, ctx, {
      ground: false, bottom: -3, papaH: 46, mamaH: 44, ariH: 28,
      papaRight: 2, mamaLeft: 2, ariLeft: 36,
      parentLeft: 6, parentH: 48, ariLeftSolo: 40
    });
    const props = propsOf(slide, 1);
    if (!items.length && props[0]) {
      out += prop(props[0], "right:8%;bottom:40%;transform:rotate(-8deg)", "orange", 132);
    }
    out += sparks("orange", 2, "story", { x: 14, y: 50, w: 16, h: 4 });
    return out;
  }

  const SCENES = {
    "cover-hook": sceneCover,
    "quick-check": sceneQuickCheck,
    "what-helped-us": sceneHelped,
    "warning": sceneWarning,
    "dont": sceneDont,
    "save-cta": sceneSave,
    "story-reel": sceneStory
  };

  /* The artwork layer. A generated base wins; otherwise the composition above.
     `art.assetUrl` is set by artwork.js once a base has been generated,
     checked for stray lettering and stored. */
  function sceneHTML(slide, ctx) {
    const art = slide.art || null;
    if (art && art.assetUrl && !art.strayText) {
      return `<img class="b-base" src="${esc(resolve(ctx, art.assetUrl))}" alt="">`;
    }
    const fn = SCENES[slide.family] || sceneCover;
    return fn(slide, ctx);
  }

  /* ==========================================================================
     THE TYPE — every readable word
     ======================================================================== */

  /* WHERE THE CLUE LABELS SIT.

     Shared by the scene and the type layer so a label lands under its own
     object rather than next to somebody else's. The scene draws the object on
     a scrap at (x, y); the label goes at (x, labelY). */
  const CLUE_SPOTS = [
    { x: 9,  y: 34, s: 210, r: -7, labelY: 51, align: "flex-start" },
    { x: 58, y: 30, s: 186, r: 6,  labelY: 45, align: "flex-start" },
    { x: 14, y: 60, s: 176, r: 8,  labelY: 74, align: "flex-start" },
    { x: 61, y: 63, s: 198, r: -5, labelY: 79, align: "flex-start" }
  ];

  /* HEADLINES ARE NO LONGER SHOUTED.

     Every headline line used to be uppercase, in one weight, at one of two
     enormous sizes. Stacked in a block over a coloured band that is a
     proclamation, and it is what tipped the whole system into looking like a
     recruitment poster.

     Now: sentence case by default, one line per headline may be marked for
     emphasis (compose.js decides, and only for a short line), sizes vary
     organically because fitSize() reads each line's own length, and a Patrick
     Hand support line carries the warmth. */
  function headlineHTML(slide, opts) {
    const o = opts || {};
    const boxW = o.boxW || 936;
    const min = o.min || 46, max = o.max || 186;
    const lines = (slide.lines || []).filter(l => l && String(l.t || "").trim());
    if (!lines.length) return "";
    const tilt = o.tilt == null ? 1 : o.tilt;

    return `<div class="s-hl${o.centred ? " is-centred" : ""}">` + lines.map((l, i) => {
      const w = (i === 0 && o.firstBoxW) ? o.firstBoxW : boxW;
      const em = l.em === true;
      /* An emphasis line is set in caps, so it is measured as caps. */
      const size = fitSize(em ? String(l.t).toUpperCase() : l.t, w, min, max);
      const rot = tilt ? (((hash(l.t + i) % 100) / 100 - 0.5) * 1.9 * tilt).toFixed(2) : 0;
      return `<span class="s-hl-l${em ? " is-em" : ""}" style="font-size:${size}px;` +
        `color:${inkOf(l.c)};transform:rotate(${rot}deg)">${esc(l.t)}</span>`;
    }).join("") + `</div>`;
  }

  /* A label. Sentence case unless it is one or two words, which is the only
     length at which caps still reads as emphasis rather than as an order. */
  const SHOUT_WORDS = 2;
  const wordsIn = (s) => String(s || "").trim().split(/\s+/).filter(Boolean).length;

  function labelHTML(text, colour, opts) {
    const o = opts || {};
    const n = wordsIn(text);
    const shout = n <= SHOUT_WORDS;
    const size = o.size || (n > 9 ? 32 : n > 5 ? 35 : 40);
    return chip("s-lab " + (shout ? "is-shout" : "is-long") + (o.cls ? " " + o.cls : ""),
      colour, text, { bgFilter: "mpcTornFine", textStyle: `font-size:${size}px` });
  }

  /* A small hand-drawn bullet, in place of the object disc. The OBJECT now
     lives in the artwork where it belongs; repeating it as a flat glyph on a
     white circle beside its own label was both redundant and the source of the
     grid-of-identical-cards look. */
  const bullet = (colour, i) =>
    `<span class="s-bullet" style="color:${inkOf(colour)}"><svg viewBox="0 0 26 26" fill="none" ` +
    `stroke="currentColor" stroke-width="3.4" stroke-linecap="round">` +
    `<path d="M13 3c6 0 10 4 10 10s-4 10-10 10S3 19 3 13 7 3 13 3"/>` +
    `<path d="M15 4c5 1 8 5 8 9"/></svg></span>`;

  /* The numbered disc survives on "what helped us" only, where the reference
     poster genuinely numbers the steps. */
  function stepDisc(i, colour) {
    return `<span class="s-disc" style="color:${inkOf(colour)}">` +
      `<span class="c-bg"></span><span class="c-t"><span class="s-disc-num">${i + 1}</span></span></span>`;
  }

  const kickerHTML = (text, colour) => text
    ? chip("s-kicker", colour || "blue", text, { bgFilter: "mpcTornFine" }) : "";

  const bandHTML = (text, colour, cls) => text
    ? `<div class="s-band ${cls || ""}">` +
      `<span class="c-bg" style="background:${inkOf(colour || "bluePale")};filter:url(#mpcTornFine)"></span>` +
      `<span class="c-t">${esc(text)}</span></div>` : "";

  const logoHTML = (ctx, style) =>
    `<img class="s-logo" src="${esc(resolve(ctx, BRAND.logo))}" alt="The Messy Parents Collection" style="${style}">`;

  const moreHTML = (n, onDark) => n
    ? `<div class="s-more${onDark ? " is-ondark" : ""}">+ ${n} more in the full guide</div>` : "";

  /* ---- per-family type layouts ----------------------------------------- */

  function typeCover(slide, ctx) {
    const geo = coverGeometry(slide);
    let out = "";
    if (slide.logo) {
      out += logoHTML(ctx, `right:7%;top:${geo.logoTop}%;width:${LOGO_W}px`);
    }
    out += `<div class="s-block" style="left:6%;right:6%;top:${geo.topPct}%">` +
      headlineHTML(slide, { boxW: 850, min: 54, max: 138 }) + `</div>`;
    if (slide.kicker) {
      out += `<div class="s-block" style="left:6%;top:${geo.sheetBottom + 3.5}%">` +
        kickerHTML(slide.kicker, "blue") + `</div>`;
    }
    return out;
  }

  function typeQuickCheck(slide, ctx) {
    const items = slide.items || [];
    let out = `<div class="s-block" style="left:5.5%;right:5.5%;top:4%">`;
    if (slide.kicker) out += kickerHTML(slide.kicker, "blue");
    out += headlineHTML(slide, { boxW: 820, min: 48, max: 122 }) + `</div>`;

    if (items.length) {
      /* Labels only, each under its own object. No discs: the objects are in
         the artwork. */
      out += items.slice(0, 4).map((it, i) => {
        const sp = CLUE_SPOTS[i] || CLUE_SPOTS[0];
        return `<div class="s-clue" style="left:${sp.x}%;top:${sp.labelY}%;width:33%">` +
          labelHTML(it.label, i % 2 ? "blue" : "orange") + `</div>`;
      }).join("");
    }
    out += moreHTML(slide.truncatedItems);
    if (slide.band) out += bandHTML(slide.band, "bluePale", "is-foot");
    return out;
  }

  function typeHelped(slide, ctx) {
    const v = slide.variant || "steps-right";
    const items = slide.items || [];
    let out = `<div class="s-block" style="left:5.5%;right:5.5%;top:4%">`;
    if (slide.kicker) out += kickerHTML(slide.kicker, "blue");
    out += headlineHTML(slide, { boxW: 640, min: 50, max: 112 }) + `</div>`;

    if (items.length && v === "steps-under") {
      out += `<div class="s-row" style="left:4%;right:4%;bottom:7%">` +
        items.map((it, i) =>
          `<div class="s-cell">${stepDisc(i, "blue")}${labelHTML(it.label, "blue")}</div>`
        ).join("") + `</div>`;
    } else if (items.length) {
      out += `<div class="s-steps" style="right:4%;top:30%;width:50%">` + items.map((it, i) => {
        const arrow = i < items.length - 1
          ? arrowMark("orange", "position:relative;display:block;width:96px;height:34px;margin:-4px 0 -4px 26%;transform:rotate(9deg)")
          : "";
        return `<div class="s-step">${stepDisc(i, "blue")}${labelHTML(it.label, "blue")}</div>${arrow}`;
      }).join("") + `</div>`;
    }
    out += moreHTML(slide.truncatedItems);
    return out;
  }

  function typeWarning(slide, ctx) {
    const items = slide.items || [];
    /* Sentence case on a soft coral patch. "Call your doctor if…" reads as a
       sentence a person would say; CALL YOUR DOCTOR IF reads as an order, and
       an order is easier to ignore. */
    let out = `<div class="s-block" style="left:6%;right:16%;top:4.5%">` +
      headlineHTML(slide, { boxW: 700, min: 50, max: 104, tilt: .4 }) + `</div>`;
    if (slide.kicker) {
      out += `<div class="s-block" style="left:6%;top:23.5%">` + kickerHTML(slide.kicker, "blue") + `</div>`;
    }
    if (items.length) {
      out += `<div class="s-steps" style="left:6%;top:32%;width:60%">` + items.map((it, i) =>
        `<div class="s-step is-tight">${bullet("coral", i)}${labelHTML(it.label, "coral")}</div>`
      ).join("") + `</div>`;
    }
    out += moreHTML(slide.truncatedItems);
    if (slide.band) out += bandHTML(slide.band, "bluePale", "is-foot");
    return out;
  }

  function typeDont(slide, ctx) {
    const items = slide.items || [];
    let out = `<div class="s-block" style="left:6%;right:20%;top:4%">` +
      headlineHTML(slide, { boxW: 700, min: 52, max: 126 }) + `</div>`;
    if (slide.kicker) {
      out += `<div class="s-block" style="left:6%;top:24%">` + kickerHTML(slide.kicker, "blue") + `</div>`;
    }
    if (items.length) {
      out += `<div class="s-steps" style="left:6%;bottom:8%;width:58%">` +
        items.map((it, i) =>
          `<div class="s-step is-tight">${bullet("coral", i)}${labelHTML(it.label, "coral", { cls: "is-crossed" })}</div>`
        ).join("") + `</div>`;
    }
    out += moreHTML(slide.truncatedItems);
    return out;
  }

  function typeSave(slide, ctx) {
    let out = `<div class="s-block" style="left:6%;right:8%;top:5%">` +
      headlineHTML(slide, { boxW: 820, min: 54, max: 136 }) +
      (slide.band
        ? `<div style="margin-top:22px;max-width:68%">` +
          chip("s-note", "creamSoft", slide.band, { bgFilter: "mpcTornFine" }) + `</div>`
        : "") +
      `</div>`;
    if (slide.cta) {
      out += `<div class="s-ctarow" style="left:6%;right:${slide.logo ? 27 : 6}%;bottom:5.4%">` +
        arrowMark("blue", "position:relative;width:118px;height:44px;flex:0 0 auto") +
        `<span class="s-ctaline">${esc(slide.cta)}</span></div>`;
    }
    if (slide.logo) out += logoHTML(ctx, "right:5.5%;bottom:4.2%;width:196px");
    return out;
  }

  function typeStory(slide, ctx) {
    const v = slide.variant || "torn-top";
    const items = slide.items || [];
    const banded = v === "band-top";
    let out = `<div class="s-block" style="left:7%;right:${banded ? 16 : 9}%;top:${banded ? 13.4 : 14.5}%">` +
      headlineHTML(slide, { boxW: banded ? 700 : 800, min: 48, max: banded ? 92 : 112, tilt: banded ? .4 : 1 }) +
      (slide.band && !items.length
        ? `<div class="s-sub" style="margin-top:26px;max-width:86%">${esc(slide.band)}</div>` : "") +
      `</div>`;
    if (items.length) {
      out += `<div class="s-steps" style="left:6%;top:${banded ? 31 : 30}%;width:82%">` +
        items.map((it, i) =>
          `<div class="s-step is-tight">${bullet("coral", i)}${labelHTML(it.label, "coral")}</div>`
        ).join("") +
        (slide.truncatedItems
          ? `<div class="s-more is-inline">+ ${slide.truncatedItems} more in the full guide</div>` : "") +
        `</div>`;
    }
    if (slide.cta) {
      out += `<div class="s-block" style="left:0;right:0;top:${banded ? 63 : 48}%;text-align:center">` +
        chip("s-pill is-oncream", "creamSoft", slide.cta, { bgFilter: "mpcTornFine" }) + `</div>`;
    }
    return out;
  }

  const TYPES = {
    "cover-hook": typeCover,
    "quick-check": typeQuickCheck,
    "what-helped-us": typeHelped,
    "warning": typeWarning,
    "dont": typeDont,
    "save-cta": typeSave,
    "story-reel": typeStory
  };

  /* ==========================================================================
     ONE SLIDE
     ======================================================================== */
  function frameHTML(slide, ctx, isStory) {
    const c = ctx || {};
    const s = slide || {};
    const family = s.family || (isStory ? "story-reel" : "cover-hook");
    const type = TYPES[family] || typeCover;
    const idx = (c.index != null && c.total) ? `${c.index + 1}/${c.total}` : "";

    return `<div class="mpc-slide${isStory ? " is-story" : ""} is-${esc(family)} v-${esc(s.variant || "default")}` +
      `${onBlue(family) ? " on-blue" : ""}">` +
      `<div class="s-scene">${sceneHTML(s, c)}</div>` +
      `<div class="s-grain"></div>` +
      `<div class="s-type">${type(s, c)}` +
      (idx && !isStory ? `<span class="s-num">${esc(idx)}</span>` : "") +
      `</div></div>`;
  }

  const slideHTML = (slide, ctx) => frameHTML(slide, ctx, false);
  const storyHTML = (frame, ctx) => frameHTML(frame, ctx, true);

  /* ==========================================================================
     THE STYLESHEET
     ======================================================================== */
  function css() {
    return `
.mpc-slide{
  /* Straight out of assets/css/tokens.css. Nothing here is invented, and the
     two UI colours (--blue #0b62c4, --orange #ff4500) are deliberately absent:
     they are for things a reader clicks, not for artwork. */
  --mpc-cream:#fbf0d3;
  --mpc-cream-soft:#fdf8ec;
  --mpc-paper:#f7ecd2;
  --mpc-ink:#211d18;
  --mpc-ink-hand:#2b2622;
  --mpc-blue:#3f6fa3;
  --mpc-blue-pale:#c9dced;
  --mpc-blue-wash:#e7f0fb;
  --mpc-orange:#e2601f;
  --mpc-coral:#d4553a;
  --mpc-coral-fill:#f9e2da;
  --mpc-amber:#c07f1e;
  --mpc-amber-fill:#fdf1d8;
  --mpc-rule:#cdbf9f;

  position:relative; overflow:hidden; isolation:isolate;
  width:${SIZE.carousel.width}px; height:${SIZE.carousel.height}px; flex:0 0 auto;
  background:var(--mpc-cream); color:var(--mpc-ink);
  font-family:"Nunito", ui-sans-serif, system-ui, sans-serif;
  box-sizing:border-box; -webkit-font-smoothing:antialiased;
}
.mpc-slide.is-story{ width:${SIZE.story.width}px; height:${SIZE.story.height}px; }
.mpc-slide *, .mpc-slide *::before, .mpc-slide *::after{ box-sizing:border-box; }

/* ---- layers ---------------------------------------------------------- */
.mpc-slide .s-scene,
.mpc-slide .s-grain,
.mpc-slide .s-type{ position:absolute; inset:0; }
.mpc-slide .s-scene{ z-index:1; overflow:hidden; }
.mpc-slide .s-grain{ z-index:2; pointer-events:none;
  background-image:var(--paper-img); background-size:cover; background-position:center;
  mix-blend-mode:multiply; opacity:.3; }
.mpc-slide .s-type{ z-index:3; }

/* ---- scene primitives ------------------------------------------------- */
.mpc-slide .b-field{ position:absolute; inset:-2%; }
.mpc-slide .b-base{ position:absolute; inset:0; width:100%; height:100%; object-fit:cover; }
/* A patch, not a band. Uneven corner radii plus a brush filter: there is no
   rectangle left in the scene layer, and rectangles are what the
   recruitment-poster look was built out of. */
.mpc-slide .b-patch{ position:absolute; }
.mpc-slide .b-scrap{ position:absolute; box-shadow:0 14px 34px rgba(33,29,24,.13); }

.mpc-slide .b-char{ position:absolute; aspect-ratio:var(--ar); overflow:hidden; }
.mpc-slide .b-char img{ position:absolute; max-width:none; }

.mpc-slide .b-spark{ position:absolute; display:block; z-index:5; }
.mpc-slide .b-spark svg, .mpc-slide .b-mark svg{ width:100%; height:100%; display:block; }
.mpc-slide .b-mark{ position:absolute; display:block; z-index:5; }

/* An object drawn into the SCENE, at scene scale — the thing the guide is
   actually about, sitting in the picture rather than repeated as an icon
   beside its own caption. */
.mpc-slide .b-prop{ position:absolute; display:block; z-index:4; }
.mpc-slide .b-prop-bg{ position:absolute; inset:-14%; background:var(--mpc-cream-soft);
  border-radius:46% 54% 50% 50% / 52% 48% 52% 48%; filter:url(#mpcTornFine); opacity:.92; }
.mpc-slide .b-prop-art{ position:absolute; inset:8%; }
.mpc-slide .b-prop-art svg{ width:100%; height:100%; }

/* ---- painted chips ----------------------------------------------------
   Background and text are separate nodes: the background is displaced by a
   turbulence filter to give it a torn edge, and the text is NEVER touched by
   one. A filter on a text node is a spelling bug. */
.mpc-slide .s-kicker, .mpc-slide .s-lab, .mpc-slide .s-pill,
.mpc-slide .s-band, .mpc-slide .s-disc, .mpc-slide .s-note{ position:relative; display:inline-block; }
.mpc-slide .c-bg{ position:absolute; inset:0; border-radius:inherit; z-index:0; }
.mpc-slide .c-t{ position:relative; z-index:1; display:block; }

/* ---- type -------------------------------------------------------------
   Mixed case, Baloo 2 at 700 rather than 800, and sizes that vary with each
   line's own length. Uppercase survives only on .is-em, which compose.js puts
   on at most one short line per headline. */
.mpc-slide .s-block{ position:absolute; }
.mpc-slide .s-hl{ display:flex; flex-direction:column; align-items:flex-start; gap:0; }
.mpc-slide .s-hl.is-centred{ align-items:center; text-align:center; }
.mpc-slide .s-hl-l{
  display:block; font-family:"Baloo 2","Trebuchet MS",sans-serif; font-weight:700;
  line-height:1.02; letter-spacing:-.008em;
  transform-origin:left center; white-space:nowrap;
}
.mpc-slide .s-hl-l.is-em{
  font-weight:800; text-transform:uppercase; letter-spacing:.005em; line-height:.98;
}
.mpc-slide .s-hl.is-centred .s-hl-l{ transform-origin:center; }

.mpc-slide .s-kicker{ border-radius:9px; margin:0 0 16px; }
.mpc-slide .s-kicker .c-t{
  color:var(--mpc-ink); font-family:"Nunito",sans-serif; font-weight:800; font-size:29px;
  letter-spacing:.11em; text-transform:uppercase; padding:11px 22px 12px;
}
/* Patrick Hand for the warm support lines — the one place the system is
   allowed to sound like handwriting rather than print. */
.mpc-slide .s-sub{
  font-family:"Patrick Hand", ui-rounded, system-ui, sans-serif; font-weight:400;
  -webkit-text-stroke:.4px currentColor;
  font-size:52px; line-height:1.16; color:var(--mpc-ink-hand);
}
.mpc-slide .s-note{ border-radius:12px; }
.mpc-slide .s-note .c-t{
  font-family:"Patrick Hand", ui-rounded, system-ui, sans-serif; font-weight:400;
  -webkit-text-stroke:.4px currentColor;
  font-size:48px; line-height:1.14; color:var(--mpc-ink-hand); padding:14px 22px 16px;
}

.mpc-slide .s-band{ position:absolute; left:6%; right:6%; display:block; border-radius:16px; }
.mpc-slide .s-band .c-t{
  color:var(--mpc-ink); font-family:"Patrick Hand", ui-rounded, sans-serif; font-weight:400;
  -webkit-text-stroke:.4px currentColor;
  font-size:46px; letter-spacing:0; text-align:center; padding:18px 26px 20px;
}
.mpc-slide .s-band.is-foot{ bottom:4.5%; }
.mpc-slide.is-story .s-band.is-foot{ bottom:15%; }

/* labels */
.mpc-slide .s-lab{ border-radius:8px; max-width:100%; min-width:0; }
.mpc-slide .s-lab .c-t{
  color:var(--mpc-cream-soft); font-family:"Nunito",sans-serif; font-weight:800;
  line-height:1.2; padding:10px 18px 12px;
  overflow-wrap:break-word; word-break:normal; hyphens:none;
}
.mpc-slide .s-lab.is-shout .c-t{ text-transform:uppercase; letter-spacing:.03em; }
.mpc-slide .s-lab.is-crossed{ position:relative; }
.mpc-slide .s-lab.is-crossed::after{
  content:""; position:absolute; left:-2%; top:52%; width:104%; height:7px; z-index:2;
  background:var(--mpc-ink); opacity:.55; transform:rotate(-2.5deg); border-radius:6px;
}

/* a hand-drawn bullet where an icon disc used to be */
.mpc-slide .s-bullet{ flex:0 0 auto; display:block; width:34px; height:34px; margin-top:6px; }
.mpc-slide .s-bullet svg{ width:100%; height:100%; }

/* the numbered disc survives on "what helped us" only */
.mpc-slide .s-disc{ width:112px; height:112px; border-radius:50%; flex:0 0 auto; }
.mpc-slide .s-disc .c-bg{ background:var(--mpc-cream-soft); filter:url(#mpcTornFine);
  box-shadow:0 8px 20px rgba(33,29,24,.14); }
.mpc-slide .s-disc .c-t{ display:flex; align-items:center; justify-content:center; width:100%; height:100%; }
.mpc-slide .s-disc-num{ font-family:"Baloo 2",sans-serif; font-weight:800; font-size:56px; line-height:1; }
.mpc-slide.is-story .s-disc{ width:96px; height:96px; }
.mpc-slide.is-story .s-disc-num{ font-size:48px; }

.mpc-slide .s-clue{ position:absolute; display:flex; flex-direction:column; }
.mpc-slide .s-steps{ position:absolute; display:flex; flex-direction:column; gap:18px; }
.mpc-slide .s-step{ display:flex; align-items:center; gap:18px; }
.mpc-slide .s-step.is-tight{ align-items:flex-start; gap:14px; }
.mpc-slide .s-step .s-lab{ flex:1 1 auto; min-width:0; }
.mpc-slide .s-row{ position:absolute; display:flex; gap:20px; align-items:flex-start; justify-content:space-between; }
.mpc-slide .s-cell{ flex:1 1 0; display:flex; flex-direction:column; align-items:center; gap:12px; text-align:center; }
.mpc-slide .s-cell .c-t{ text-align:center; }

.mpc-slide .s-more{ position:absolute; left:5.5%; bottom:2.2%; font-size:26px; font-weight:700;
  color:var(--mpc-ink); background:rgba(253,248,236,.9); padding:5px 12px 6px;
  border-radius:7px; }
.mpc-slide .s-more.is-inline,
.mpc-slide.on-blue .s-more.is-inline{ position:static; background:none; color:var(--mpc-ink);
  opacity:.62; margin-top:4px; padding:0; }

.mpc-slide .s-ctarow{ position:absolute; display:flex; align-items:center; gap:22px; }
.mpc-slide .s-ctaline{
  font-family:"Baloo 2",sans-serif; font-weight:700; font-size:52px;
  letter-spacing:0; color:var(--mpc-ink);
  border-bottom:8px solid var(--mpc-blue); padding-bottom:5px;
}
.mpc-slide .s-pill{ border-radius:70px; }
.mpc-slide .s-pill .c-t{
  color:var(--mpc-ink); font-family:"Nunito",sans-serif; font-weight:800; font-size:38px;
  letter-spacing:.04em; padding:22px 46px;
}
.mpc-slide .s-pill.is-oncream .c-t{ color:var(--mpc-ink); }
.mpc-slide .s-logo{ position:absolute; height:auto; display:block; z-index:4; }
.mpc-slide .s-num{
  position:absolute; right:3.4%; bottom:2.2%; font-weight:800; font-size:28px;
  letter-spacing:.1em; color:var(--mpc-ink); opacity:.5;
}
.mpc-slide.on-blue .s-num{ color:var(--mpc-cream); opacity:.75; }
`;
  }

  /* --------------------------------------------------------------------------
     A COMPLETE STANDALONE DOCUMENT

     `tokensCss` INLINES assets/css/tokens.css, and `paperUri` inlines the
     paper texture. That is not an optimisation, it is the only thing that
     works in the export renderer: setContent() gives the page an about:blank
     URL, so a <link> to /assets/css/tokens.css cannot resolve — the page would
     render with no custom properties and no fonts at all, which reads as a
     design change rather than as a bug.

     `cssHref` remains for the browser, where a root-absolute link does
     resolve. Pass one or the other, never both.
     ------------------------------------------------------------------------ */
  function documentHTML(innerHTML, opts) {
    const o = opts || {};
    const tokens = o.tokensCss
      ? `<style>${o.tokensCss}</style>`
      : `<link rel="stylesheet" href="${esc(o.cssHref || "/assets/css/tokens.css")}">`;
    const paper = o.paperUri || BRAND.paper;
    return `<!doctype html><html lang="en"><head><meta charset="utf-8">
<title>${esc(o.title || "slide")}</title>
${tokens}
<style>html,body{margin:0;padding:0;background:#fff}
:root{--paper-img:url("${paper}")}
${css()}</style>
</head><body>${FILTERS}${innerHTML}</body></html>`;
  }

  return {
    css, FILTERS, slideHTML, storyHTML, documentHTML,
    SAFE, SIZE, CHARACTERS, BRAND, INK, GROUND, OBJECT_PATHS,
    esc, fitSize, objectSVG, sceneHTML, resolve, chip
  };
});
